
-- ==============================================================================
-- 1. CORREÇÃO CRÍTICA: PERMISSÕES DE USUÁRIO (TRIGGER & PROFILES)
-- ==============================================================================

-- Remove trigger antigo se existir para evitar conflitos
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Garante tabela de perfis
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'USER',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilita segurança (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Função Trigger com SECURITY DEFINER (Corrige o erro de permissão ao criar usuário)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Vendedor'), 
    COALESCE(new.raw_user_meta_data->>'avatar_url', ''), 
    'USER' -- Define papel padrão
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

-- Recria o trigger
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ==============================================================================
-- 2. TABELA DE SOLUÇÕES (CORREÇÃO BIGINT)
-- ==============================================================================

-- Cria a tabela garantindo que ID seja BIGINT para suportar Date.now()
CREATE TABLE IF NOT EXISTS public.solutions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- BIGINT é essencial aqui
    solucao TEXT NOT NULL,
    promessa TEXT,
    descricao TEXT,
    categoria TEXT,
    subcategoria TEXT,
    duracao TEXT,
    maturidade TEXT,
    fee_mensal TEXT,
    valor_base_num NUMERIC DEFAULT 0,
    variaveis_opcionais JSONB DEFAULT '[]'::jsonb,
    dica_venda TEXT,
    link TEXT,
    entregaveis TEXT[],
    diferenciais TEXT[],
    publico_alvo TEXT,
    resultado_esperado TEXT,
    is_favorite BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.solutions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.solutions;
CREATE POLICY "Enable read access for all users" ON public.solutions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.solutions;
CREATE POLICY "Enable all access for authenticated users" ON public.solutions FOR ALL USING (auth.role() = 'authenticated');


-- ==============================================================================
-- 3. TABELAS DE CONFIGURAÇÃO (JSONB)
-- ==============================================================================

-- App Config (Branding, Logos)
CREATE TABLE IF NOT EXISTS public.app_config (
    id TEXT PRIMARY KEY,
    content JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read app_config" ON public.app_config;
CREATE POLICY "Public read app_config" ON public.app_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Auth update app_config" ON public.app_config;
CREATE POLICY "Auth update app_config" ON public.app_config FOR ALL USING (auth.role() = 'authenticated');

-- AI Config (API Keys, Prompts)
CREATE TABLE IF NOT EXISTS public.ai_config (
    id TEXT PRIMARY KEY,
    content JSONB
);
ALTER TABLE public.ai_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read ai_config" ON public.ai_config;
CREATE POLICY "Public read ai_config" ON public.ai_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Auth update ai_config" ON public.ai_config;
CREATE POLICY "Auth update ai_config" ON public.ai_config FOR ALL USING (auth.role() = 'authenticated');

-- Essência (Textos da Cultura)
CREATE TABLE IF NOT EXISTS public.essencia_config (
    id TEXT PRIMARY KEY,
    content JSONB
);
ALTER TABLE public.essencia_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read essencia_config" ON public.essencia_config;
CREATE POLICY "Public read essencia_config" ON public.essencia_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Auth update essencia_config" ON public.essencia_config;
CREATE POLICY "Auth update essencia_config" ON public.essencia_config FOR ALL USING (auth.role() = 'authenticated');


-- ==============================================================================
-- 4. HISTÓRICO DE PROPOSTAS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.proposals_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_name TEXT,
    industry TEXT,
    total_value NUMERIC,
    consultant TEXT,
    items JSONB,
    metadata JSONB,
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.proposals_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Auth read proposals" ON public.proposals_history;
CREATE POLICY "Auth read proposals" ON public.proposals_history FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Auth insert proposals" ON public.proposals_history;
CREATE POLICY "Auth insert proposals" ON public.proposals_history FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Auth update proposals" ON public.proposals_history;
CREATE POLICY "Auth update proposals" ON public.proposals_history FOR UPDATE USING (auth.role() = 'authenticated');

